name: debugger visualizer v2
on: [push, pull_request]
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - run: rustup toolchain install stable --profile minimal
      - name: Install GDB
        run: sudo apt-get update && sudo apt-get install -y gdb
      - run: cargo fetch --locked
      - run: cargo fmt --all -- --check
      - run: cargo clippy --offline --workspace --all-targets --all-features -- -D warnings
      - run: cargo test --offline --workspace --all-features
      - run: cargo xtask compiler
        timeout-minutes: 5
      - run: cargo xtask integration --faults --lto --relocated
        timeout-minutes: 5
